export const COUNTRY_META = {
  '004': { a2: 'AF', a3: 'AFG', ooklaName: 'Afghanistan' },
  '008': { a2: 'AL', a3: 'ALB', ooklaName: 'Albania' },
  '012': { a2: 'DZ', a3: 'DZA', ooklaName: 'Algeria' },
  '020': { a2: 'AD', a3: 'AND', ooklaName: 'Andorra' },
  '024': { a2: 'AO', a3: 'AGO', ooklaName: 'Angola' },
  '028': { a2: 'AG', a3: 'ATG', ooklaName: 'Antigua and Barbuda' },
  '031': { a2: 'AZ', a3: 'AZE', ooklaName: 'Azerbaijan' },
  '032': { a2: 'AR', a3: 'ARG', ooklaName: 'Argentina' },
  '036': { a2: 'AU', a3: 'AUS', ooklaName: 'Australia' },
  '040': { a2: 'AT', a3: 'AUT', ooklaName: 'Austria' },
  '044': { a2: 'BS', a3: 'BHS', ooklaName: 'Bahamas' },
  '048': { a2: 'BH', a3: 'BHR', ooklaName: 'Bahrain' },
  '050': { a2: 'BD', a3: 'BGD', ooklaName: 'Bangladesh' },
  '051': { a2: 'AM', a3: 'ARM', ooklaName: 'Armenia' },
  '056': { a2: 'BE', a3: 'BEL', ooklaName: 'Belgium' },
  '084': { a2: 'BZ', a3: 'BLZ', ooklaName: 'Belize' },
  '064': { a2: 'BT', a3: 'BTN', ooklaName: 'Bhutan' },
  '068': { a2: 'BO', a3: 'BOL', ooklaName: 'Bolivia' },
  '070': { a2: 'BA', a3: 'BIH', ooklaName: 'Bosnia and Herzegovina' },
  '072': { a2: 'BW', a3: 'BWA', ooklaName: 'Botswana' },
  '076': { a2: 'BR', a3: 'BRA', ooklaName: 'Brazil' },
  '096': { a2: 'BN', a3: 'BRN', ooklaName: 'Brunei' },
  '100': { a2: 'BG', a3: 'BGR', ooklaName: 'Bulgaria' },
  '104': { a2: 'MM', a3: 'MMR', ooklaName: 'Myanmar' },
  '108': { a2: 'BI', a3: 'BDI', ooklaName: 'Burundi' },
  '112': { a2: 'BY', a3: 'BLR', ooklaName: 'Belarus' },
  '116': { a2: 'KH', a3: 'KHM', ooklaName: 'Cambodia' },
  '120': { a2: 'CM', a3: 'CMR', ooklaName: 'Cameroon' },
  '124': { a2: 'CA', a3: 'CAN', ooklaName: 'Canada' },
  '140': { a2: 'CF', a3: 'CAF', ooklaName: 'Central African Republic' },
  '144': { a2: 'LK', a3: 'LKA', ooklaName: 'Sri Lanka' },
  '148': { a2: 'TD', a3: 'TCD', ooklaName: 'Chad' },
  '152': { a2: 'CL', a3: 'CHL', ooklaName: 'Chile' },
  '156': { a2: 'CN', a3: 'CHN', ooklaName: 'China' },
  '158': { a2: 'TW', a3: 'TWN', ooklaName: 'Taiwan' },
  '170': { a2: 'CO', a3: 'COL', ooklaName: 'Colombia' },
  '174': { a2: 'KM', a3: 'COM', ooklaName: 'Comoros' },
  '178': { a2: 'CG', a3: 'COG', ooklaName: 'Republic of the Congo' },
  '180': { a2: 'CD', a3: 'COD', ooklaName: 'Democratic Republic of the Congo' },
  '188': { a2: 'CR', a3: 'CRI', ooklaName: 'Costa Rica' },
  '191': { a2: 'HR', a3: 'HRV', ooklaName: 'Croatia' },
  '192': { a2: 'CU', a3: 'CUB', ooklaName: 'Cuba' },
  '196': { a2: 'CY', a3: 'CYP', ooklaName: 'Cyprus' },
  '203': { a2: 'CZ', a3: 'CZE', ooklaName: 'Czech Republic' },
  '204': { a2: 'BJ', a3: 'BEN', ooklaName: 'Benin' },
  '208': { a2: 'DK', a3: 'DNK', ooklaName: 'Denmark' },
  '214': { a2: 'DO', a3: 'DOM', ooklaName: 'Dominican Republic' },
  '218': { a2: 'EC', a3: 'ECU', ooklaName: 'Ecuador' },
  '222': { a2: 'SV', a3: 'SLV', ooklaName: 'El Salvador' },
  '231': { a2: 'ET', a3: 'ETH', ooklaName: 'Ethiopia' },
  '232': { a2: 'ER', a3: 'ERI', ooklaName: 'Eritrea' },
  '233': { a2: 'EE', a3: 'EST', ooklaName: 'Estonia' },
  '246': { a2: 'FI', a3: 'FIN', ooklaName: 'Finland' },
  '250': { a2: 'FR', a3: 'FRA', ooklaName: 'France' },
  '262': { a2: 'DJ', a3: 'DJI', ooklaName: 'Djibouti' },
  '266': { a2: 'GA', a3: 'GAB', ooklaName: 'Gabon' },
  '268': { a2: 'GE', a3: 'GEO', ooklaName: 'Georgia' },
  '270': { a2: 'GM', a3: 'GMB', ooklaName: 'Gambia' },
  '276': { a2: 'DE', a3: 'DEU', ooklaName: 'Germany' },
  '288': { a2: 'GH', a3: 'GHA', ooklaName: 'Ghana' },
  '300': { a2: 'GR', a3: 'GRC', ooklaName: 'Greece' },
  '320': { a2: 'GT', a3: 'GTM', ooklaName: 'Guatemala' },
  '324': { a2: 'GN', a3: 'GIN', ooklaName: 'Guinea' },
  '328': { a2: 'GY', a3: 'GUY', ooklaName: 'Guyana' },
  '332': { a2: 'HT', a3: 'HTI', ooklaName: 'Haiti' },
  '340': { a2: 'HN', a3: 'HND', ooklaName: 'Honduras' },
  '344': { a2: 'HK', a3: 'HKG', ooklaName: 'Hong Kong' },
  '348': { a2: 'HU', a3: 'HUN', ooklaName: 'Hungary' },
  '352': { a2: 'IS', a3: 'ISL', ooklaName: 'Iceland' },
  '356': { a2: 'IN', a3: 'IND', ooklaName: 'India' },
  '360': { a2: 'ID', a3: 'IDN', ooklaName: 'Indonesia' },
  '364': { a2: 'IR', a3: 'IRN', ooklaName: 'Iran' },
  '368': { a2: 'IQ', a3: 'IRQ', ooklaName: 'Iraq' },
  '372': { a2: 'IE', a3: 'IRL', ooklaName: 'Ireland' },
  '376': { a2: 'IL', a3: 'ISR', ooklaName: 'Israel' },
  '380': { a2: 'IT', a3: 'ITA', ooklaName: 'Italy' },
  '384': { a2: 'CI', a3: 'CIV', ooklaName: "Cote d'Ivoire" },
  '388': { a2: 'JM', a3: 'JAM', ooklaName: 'Jamaica' },
  '392': { a2: 'JP', a3: 'JPN', ooklaName: 'Japan' },
  '398': { a2: 'KZ', a3: 'KAZ', ooklaName: 'Kazakhstan' },
  '400': { a2: 'JO', a3: 'JOR', ooklaName: 'Jordan' },
  '404': { a2: 'KE', a3: 'KEN', ooklaName: 'Kenya' },
  '408': { a2: 'KP', a3: 'PRK', ooklaName: 'North Korea' },
  '410': { a2: 'KR', a3: 'KOR', ooklaName: 'South Korea' },
  '414': { a2: 'KW', a3: 'KWT', ooklaName: 'Kuwait' },
  '417': { a2: 'KG', a3: 'KGZ', ooklaName: 'Kyrgyzstan' },
  '418': { a2: 'LA', a3: 'LAO', ooklaName: 'Laos' },
  '422': { a2: 'LB', a3: 'LBN', ooklaName: 'Lebanon' },
  '426': { a2: 'LS', a3: 'LSO', ooklaName: 'Lesotho' },
  '428': { a2: 'LV', a3: 'LVA', ooklaName: 'Latvia' },
  '430': { a2: 'LR', a3: 'LBR', ooklaName: 'Liberia' },
  '434': { a2: 'LY', a3: 'LBY', ooklaName: 'Libya' },
  '440': { a2: 'LT', a3: 'LTU', ooklaName: 'Lithuania' },
  '442': { a2: 'LU', a3: 'LUX', ooklaName: 'Luxembourg' },
  '446': { a2: 'MO', a3: 'MAC', ooklaName: 'Macau' },
  '450': { a2: 'MG', a3: 'MDG', ooklaName: 'Madagascar' },
  '454': { a2: 'MW', a3: 'MWI', ooklaName: 'Malawi' },
  '458': { a2: 'MY', a3: 'MYS', ooklaName: 'Malaysia' },
  '462': { a2: 'MV', a3: 'MDV', ooklaName: 'Maldives' },
  '466': { a2: 'ML', a3: 'MLI', ooklaName: 'Mali' },
  '470': { a2: 'MT', a3: 'MLT', ooklaName: 'Malta' },
  '478': { a2: 'MR', a3: 'MRT', ooklaName: 'Mauritania' },
  '480': { a2: 'MU', a3: 'MUS', ooklaName: 'Mauritius' },
  '484': { a2: 'MX', a3: 'MEX', ooklaName: 'Mexico' },
  '496': { a2: 'MN', a3: 'MNG', ooklaName: 'Mongolia' },
  '498': { a2: 'MD', a3: 'MDA', ooklaName: 'Moldova' },
  '499': { a2: 'ME', a3: 'MNE', ooklaName: 'Montenegro' },
  '504': { a2: 'MA', a3: 'MAR', ooklaName: 'Morocco' },
  '508': { a2: 'MZ', a3: 'MOZ', ooklaName: 'Mozambique' },
  '512': { a2: 'OM', a3: 'OMN', ooklaName: 'Oman' },
  '516': { a2: 'NA', a3: 'NAM', ooklaName: 'Namibia' },
  '524': { a2: 'NP', a3: 'NPL', ooklaName: 'Nepal' },
  '528': { a2: 'NL', a3: 'NLD', ooklaName: 'Netherlands' },
  '554': { a2: 'NZ', a3: 'NZL', ooklaName: 'New Zealand' },
  '558': { a2: 'NI', a3: 'NIC', ooklaName: 'Nicaragua' },
  '562': { a2: 'NE', a3: 'NER', ooklaName: 'Niger' },
  '566': { a2: 'NG', a3: 'NGA', ooklaName: 'Nigeria' },
  '578': { a2: 'NO', a3: 'NOR', ooklaName: 'Norway' },
  '586': { a2: 'PK', a3: 'PAK', ooklaName: 'Pakistan' },
  '591': { a2: 'PA', a3: 'PAN', ooklaName: 'Panama' },
  '600': { a2: 'PY', a3: 'PRY', ooklaName: 'Paraguay' },
  '598': { a2: 'PG', a3: 'PNG', ooklaName: 'Papua New Guinea' },
  '604': { a2: 'PE', a3: 'PER', ooklaName: 'Peru' },
  '608': { a2: 'PH', a3: 'PHL', ooklaName: 'Philippines' },
  '616': { a2: 'PL', a3: 'POL', ooklaName: 'Poland' },
  '620': { a2: 'PT', a3: 'PRT', ooklaName: 'Portugal' },
  '624': { a2: 'GW', a3: 'GNB', ooklaName: 'Guinea-Bissau' },
  '626': { a2: 'TL', a3: 'TLS', ooklaName: 'Timor-Leste' },
  '634': { a2: 'QA', a3: 'QAT', ooklaName: 'Qatar' },
  '642': { a2: 'RO', a3: 'ROU', ooklaName: 'Romania' },
  '643': { a2: 'RU', a3: 'RUS', ooklaName: 'Russia' },
  '646': { a2: 'RW', a3: 'RWA', ooklaName: 'Rwanda' },
  '682': { a2: 'SA', a3: 'SAU', ooklaName: 'Saudi Arabia' },
  '686': { a2: 'SN', a3: 'SEN', ooklaName: 'Senegal' },
  '688': { a2: 'RS', a3: 'SRB', ooklaName: 'Serbia' },
  '694': { a2: 'SL', a3: 'SLE', ooklaName: 'Sierra Leone' },
  '702': { a2: 'SG', a3: 'SGP', ooklaName: 'Singapore' },
  '703': { a2: 'SK', a3: 'SVK', ooklaName: 'Slovakia' },
  '704': { a2: 'VN', a3: 'VNM', ooklaName: 'Vietnam' },
  '705': { a2: 'SI', a3: 'SVN', ooklaName: 'Slovenia' },
  '706': { a2: 'SO', a3: 'SOM', ooklaName: 'Somalia' },
  '710': { a2: 'ZA', a3: 'ZAF', ooklaName: 'South Africa' },
  '716': { a2: 'ZW', a3: 'ZWE', ooklaName: 'Zimbabwe' },
  '724': { a2: 'ES', a3: 'ESP', ooklaName: 'Spain' },
  '729': { a2: 'SD', a3: 'SDN', ooklaName: 'Sudan' },
  '740': { a2: 'SR', a3: 'SUR', ooklaName: 'Suriname' },
  '748': { a2: 'SZ', a3: 'SWZ', ooklaName: 'Eswatini' },
  '752': { a2: 'SE', a3: 'SWE', ooklaName: 'Sweden' },
  '756': { a2: 'CH', a3: 'CHE', ooklaName: 'Switzerland' },
  '760': { a2: 'SY', a3: 'SYR', ooklaName: 'Syria' },
  '762': { a2: 'TJ', a3: 'TJK', ooklaName: 'Tajikistan' },
  '764': { a2: 'TH', a3: 'THA', ooklaName: 'Thailand' },
  '768': { a2: 'TG', a3: 'TGO', ooklaName: 'Togo' },
  '780': { a2: 'TT', a3: 'TTO', ooklaName: 'Trinidad and Tobago' },
  '784': { a2: 'AE', a3: 'ARE', ooklaName: 'United Arab Emirates' },
  '788': { a2: 'TN', a3: 'TUN', ooklaName: 'Tunisia' },
  '792': { a2: 'TR', a3: 'TUR', ooklaName: 'Turkey' },
  '795': { a2: 'TM', a3: 'TKM', ooklaName: 'Turkmenistan' },
  '800': { a2: 'UG', a3: 'UGA', ooklaName: 'Uganda' },
  '804': { a2: 'UA', a3: 'UKR', ooklaName: 'Ukraine' },
  '807': { a2: 'MK', a3: 'MKD', ooklaName: 'North Macedonia' },
  '818': { a2: 'EG', a3: 'EGY', ooklaName: 'Egypt' },
  '826': { a2: 'GB', a3: 'GBR', ooklaName: 'United Kingdom' },
  '834': { a2: 'TZ', a3: 'TZA', ooklaName: 'Tanzania' },
  '840': { a2: 'US', a3: 'USA', ooklaName: 'United States' },
  '854': { a2: 'BF', a3: 'BFA', ooklaName: 'Burkina Faso' },
  '858': { a2: 'UY', a3: 'URY', ooklaName: 'Uruguay' },
  '860': { a2: 'UZ', a3: 'UZB', ooklaName: 'Uzbekistan' },
  '862': { a2: 'VE', a3: 'VEN', ooklaName: 'Venezuela' },
  '887': { a2: 'YE', a3: 'YEM', ooklaName: 'Yemen' },
  '894': { a2: 'ZM', a3: 'ZMB', ooklaName: 'Zambia' },
  '926': { a2: 'XK', a3: 'XKX', ooklaName: 'Kosovo' },
  '275': { a2: 'PS', a3: 'PSE', ooklaName: 'Palestine' },
  '308': { a2: 'GD', a3: 'GRD', ooklaName: 'Grenada' },
}

